### PR TITLE
# 157770678 resolved request page

### PR DESCRIPTION
**Pull request by lawrenceChege**
#### What does this PR do?
* view for resolved requests on user dashboard
#### Description of Task to be completed?
a user can view the tasks they have submitted and have been approved and resolved 
#### How should this be manually tested?
* open this link [Maintenance-Tracker](https://github.com/lawrenceChege/Maintenance-Tracker)
* Download the repository or do `https://github.com/lawrenceChege/Maintenance-Tracker>`
* do a `git checkout ft-approved-157770678`
* navigate to user-dashboard.html and run on a browser 
* click the resolved  tab
#### What are the relevant pivotal tracker stories?
[#157770678](https://www.pivotaltracker.com/story/show/157770678)
#### Screenshots 

image

#### Questions:
how responsive is the page?
is the design eligible?

### CODE REVIEW

**Comment by Slinjez** [comment]
looks ok, will dm some insights on slack

**Comment by Slinjez** [comment]
The pr is well structured, nice ui... good work

**Comment by maxwellgithinji** [comment]
Nice UI, good work

**Comment by PaulKitonyi** [comment]
@lawrenceChege check out the branch you are merging into.It should be develop.

**Pull request merged**
