### PR TITLE
#157770512 Sent request tab

### PR DESCRIPTION
**Pull request by lawrenceChege**
#### What does this PR do?
* view for sent requests
#### Description of Task to be completed?
a user can view the tasks they have submitted but have not been approved
#### How should this be manually tested?
* open the this link [Maintenance-Tracker](https://github.com/lawrenceChege/Maintenance-Tracker)
* Download the repository or do `https://github.com/lawrenceChege/Maintenance-Tracker>`
* do a `git checkout ft-sent-157770512`
* navigate to user-dashboard.html and run on a browser 
* click  sent tab
#### What are the relevant pivotal tracker stories?
#157770512
#### Screenshots 
image

#### Questions:
how responsive is the page?
is the design eligible?

### CODE REVIEW

**Comment by denniswanjiru** [comment]
I'd highly recommend you use a standard font-family for good ux . 
Also your comment messages are incomplete they don't contain informative description
Recommended commit message: `[Story-type #pt-id] Commit description` eg `[Feature #123456] Add a sidenav`
Otherwise good design and well documented PR

**Comment by johnmusiu** [comment]
Good PR detail.
Cool UI design.

**Comment by lawrenceChege** [comment]
Thanks I will change to that.

**Comment by asamisellah** [comment]
I echo what Dennis has suggested. I like your working progress.

**Pull request merged**
