### PR TITLE
 157767711 log in page

### PR DESCRIPTION
**Pull request by lawrenceChege**
#### What does this PR do?
* Complete design for log in page
#### Description of Task to be completed?
*a user can log in into their account using email and a password*
#### How should this be manually tested?
* open the this link [Maintenance-Tracker](https://github.com/lawrenceChege/Maintenance-Tracker)
* Download the repository or do `https://github.com/lawrenceChege/Maintenance-Tracker>`
* do a `git checkout ft-login-157767711>`
* navigate to signin.html and run on browser 
#### What are the relevant pivotal tracker stories?
#157767711 
#### Screenshots (if appropriate)[
image

#### Questions:
how responsive is the page?
is the design eligible?

### CODE REVIEW

**Comment by joelmachango** [comment]
@lawrenceChege The design is legible. I can read everything.

**Comment by asamisellah** [comment]
Your PR is ok in my opinion

**Comment by lawrenceChege** [comment]
Thanks @joelmachango @asamisellah

**Comment by PaulKitonyi** [comment]
Your PR is good and you have a great design too.

**Pull request merged**
