### PR TITLE
#157880661 Rejected request tab

### PR DESCRIPTION
**Pull request by lawrenceChege**
#### What does this PR do?
* view for rejected requests on user dashboard
#### Description of Task to be completed?
a user can view the tasks they have submitted and have been rejected
#### How should this be manually tested?
* open this link [Maintenance-Tracker](https://github.com/lawrenceChege/Maintenance-Tracker)
* Download the repository or do `https://github.com/lawrenceChege/Maintenance-Tracker>`
* do a `git checkout ft-rejected-157880661`
* navigate to user-dashboard.html and run on a browser 
* click the rejected  tab
#### What are the relevant pivotal tracker stories?
[#157880661](https://www.pivotaltracker.com/story/show/157880661)
#### Screenshots 

image

#### Questions:
how responsive is the page?
is the design eligible?

### CODE REVIEW

**Comment by Slinjez** [comment]
nice improvements on the ui...this is more presentable....good work

**Comment by johnmusiu** [comment]
UI font more legible. great
PR looks good

You seem to be merging into other feature branches consistently, what's up?

**Comment by lawrenceChege** [comment]
@johnmusiu I created a user-dashboard branch.
I have been creating feature branches from it. 
when I am done with the user dashboard I will merge with develop.

**Comment by johnmusiu** [comment]
Alright buddy, keep hacking.

**Comment by maxwellgithinji** [comment]
Awesome Implementation, Keep it up.

**Comment by zakhusayn** [comment]
great!! Love the new improved UI

**Comment by lawrenceChege** [comment]
thanks y'all

**Pull request merged**
