### PR TITLE
Ft landing page 157774780

### PR DESCRIPTION
**Pull request by lawrenceChege**

### CODE REVIEW

**Comment by lawrenceChege** [comment]
#### What does this PR do?
Complete the landing page of Maintenance Tracker UI
#### Description of Task to be completed?
The landing page is complete
The links to other pages are working
The font-awesome icons are working
goole fonts are working 
#### How should this be manually tested?
clone or download repository
navigate to Maintenance Tracker/UI/
open index.html on a browser

#### What are the relevant pivotal tracker stories?
#157774780  
#### Screenshots (if appropriate)
here is a link to the screenshot
https://ibb.co/hvLHVo
#### Questions:
Is the design simple and responsive?
Is the design appealing?

**Comment by joelmachango** [comment]
@lawrenceChege wow! This is really nice. I love how detailed your PR message is.

**Comment by zakhusayn** [comment]
i like how you wrote your PR and also the commits. Well done!!

**Comment by mmosoroohh** [comment]
looks great and detailed..

**Comment by johnmusiu** [comment]
The design is appealing. Pull request well written

**Pull request merged**
