### PR TITLE
# 157770262 user dashboard

### PR DESCRIPTION
**Pull request by lawrenceChege**
#### What does this PR do?
* layout design for user dashboard
#### Description of Task to be completed?
*after login in a user can access
   * new request tab
   * sent requests tab
   * approved requests tab
   * rejected requests tab
   * resolved request tab
   * messages tab
#### How should this be manually tested?
* open the this link [Maintenance-Tracker](https://github.com/lawrenceChege/Maintenance-Tracker)
* Download the repository or do `https://github.com/lawrenceChege/Maintenance-Tracker>`
* do a `git checkout ft-use-dashboard-157770262`
* navigate to user-dashboard.html and run on a browser 
#### Any background context you want to provide?
it is the base branch for user dashboard
#### What are the relevant pivotal tracker stories?
#157770262
#### Screenshots (if appropriate)[
image

#### Questions:
how responsive is the page?
is the design eligible?

### CODE REVIEW

**Comment by asamisellah** [comment]
Good PR. Make your side-bar align with the left side of your page.

**Comment by PaulKitonyi** [comment]
Wow.Nice interface.Consider @asamisellah's feedback.
Also PLEASE!!!!!! Do not merge into MASTER.

**Comment by joelmachango** [comment]
@PaulKitonyi Has raised an important point. Change the base branch to develop. @lawrenceChege Check out this [resource ](https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/)

**Comment by lawrenceChege** [comment]
I implemented feedback .thanks guys

**Pull request merged**
