### PR TITLE
#157767990 admin dashboard

### PR DESCRIPTION
**Pull request by lawrenceChege**
#### What does this PR do?
* admin dashboard main page
#### Description of Task to be completed?
an admin user can view the tasks that have been submitted and their status
#### How should this be manually tested?
* open this link [Maintenance-Tracker](https://github.com/lawrenceChege/Maintenance-Tracker)
* Download the repository or do `https://github.com/lawrenceChege/Maintenance-Tracker>`
* do a `git checkout ft-admin-dashboard`
* navigate to admin-dashboard.html and run on a browser 
#### What are the relevant pivotal tracker stories?
[#157767990](https://www.pivotaltracker.com/story/show/157767990)
#### Screenshots 

image

#### Questions:
how responsive is the page?
is the design eligible?

### CODE REVIEW

**Comment by dalaineme** [comment]
I think the green Approved on the Status column looks neat... maybe apply the same styling to the rest of the column items.

**Comment by denniswanjiru** [comment]
Nice design and PR is detailed

**Comment by Slinjez** [comment]
Nice pr, the green idea would look great

**Comment by lawrenceChege** [comment]
thank you. will apply

**Pull request merged**
