### PR TITLE
# 157769746 Admin dashboard approved request tab

### PR DESCRIPTION
**Pull request by lawrenceChege**
#### What does this PR do?
Admin dashboard resolved requests tab 
#### Description of Task to be completed?
* after accessing  the admin dashboard
* navigate to resolved request tab on side bar
* test resolve buttons

### How should this be manually tested?
* open the this link [Maintenance-Tracker](https://github.com/lawrenceChege/Maintenance-Tracker)
* Download the repository or do `https://github.com/lawrenceChege/Maintenance-Tracker>`
* do a `git checkout ft-admin-received-157769746`
* navigate to admin-dashboard.html and run on a browser 
#### What are the relevant pivotal tracker stories?
[#157769746](https://www.pivotaltracker.com/story/show/157769746)
#### Screenshots (if appropriate)[
image

#### Questions:
how responsive is the page?
is the design eligible?

### CODE REVIEW

**Comment by asamisellah** [comment]
This design looks much cleaner.

**Comment by asamisellah** [comment]
Let me check for responsiveness

**Comment by asamisellah** [comment]
The text is legible

**Comment by ghost** [comment]
It's actually good. Looks clean and simple.

**Comment by joelmachango** [comment]
The colored buttons have made a significant improvement. Nice job @lawrenceChege

**Pull request merged**
