### PR TITLE
# 157770588 Approved request page

### PR DESCRIPTION
**Pull request by lawrenceChege**
#### What does this PR do?
* view for approved requests on user dashboard
#### Description of Task to be completed?
a user can view the tasks they have submitted and approved
#### How should this be manually tested?
* open the this link [Maintenance-Tracker](https://github.com/lawrenceChege/Maintenance-Tracker)
* Download the repository or do `https://github.com/lawrenceChege/Maintenance-Tracker>`
* do a `git checkout ft-approved-157770588`
* navigate to user-dashboard.html and run on a browser 
* click approved tab
#### What are the relevant pivotal tracker stories?
[#157770588](https://www.pivotaltracker.com/story/show/157770588)
#### Screenshots 

image

#### Questions:
how responsive is the page?
is the design eligible?

### CODE REVIEW

**Comment by PaulKitonyi** [comment]
Nice UI and PR.Only that you wanna change your base branch to avoid merging to master.

**Comment by aokilipa** [comment]
Looks Good, but always check the branch you want to merge to..

**Comment by joelmachango** [comment]
yap @antokish Is right. Merge to develop @lawrenceChege 

I like the disign.

**Comment by lawrenceChege** [comment]
thanks @antokish @joelmachango @PaulKitonyi  i hadn't noticed that

**Comment by maxwellgithinji** [comment]
@lawrenceChege looks good, but you should be merging to the develop branch

**Pull request merged**
